version: 0.1
phases:
  install:
    commands:
      - apt-get upgrade -y
      - apt-get update -y
      - apt install nodejs -y
      - npm install -g @angular/cli
  build:
    commands:
      - npm install
      - ng build --prod  --configuration=production
  post_build:
    commands:
       - aws s3 cp dist/koyo s3://koyo-ui --recursive --acl public-read
       - aws configure set preview.cloudfront true
       - aws cloudfront create-invalidation --distribution-id E1SDEW5US4ZD0Q --paths '/*'
# artifacts:
#   files:
#     - '**/*'
#   base-directory: 'dist*'
#   discard-paths: yes
